#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.dataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Progra5")]
	public partial class conexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public conexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public conexionLinqDataContext() :
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Progra5ConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_ActualizarOrden")]
		public ISingleResult<PA_ActualizarOrdenResult> PA_ActualizarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMesa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, idMesa, idUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<PA_ActualizarOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_ActualizarOrdenDetalle")]
		public ISingleResult<PA_ActualizarOrdenDetalleResult> PA_ActualizarOrdenDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantidad, idOrden, idProducto, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<PA_ActualizarOrdenDetalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_ActualizarUsuario")]
		public ISingleResult<PA_ActualizarUsuarioResult> PA_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string nombrePersona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombrePersona, apellido, correo, telefono, cedula, contrasena, idTipoUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((ISingleResult<PA_ActualizarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_CancelarOrden")]
		public ISingleResult<PA_CancelarOrdenResult> PA_CancelarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_CancelarOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_CobrarOrden")]
		public ISingleResult<PA_CobrarOrdenResult> PA_CobrarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_CobrarOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_CrearOrden")]
		public ISingleResult<PA_CrearOrdenResult> PA_CrearOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMesa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMesa, idUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<PA_CrearOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_EliminarOrden")]
		public ISingleResult<PA_EliminarOrdenResult> PA_EliminarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_EliminarOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_EliminarOrdenDetalle")]
		public ISingleResult<PA_EliminarOrdenDetalleResult> PA_EliminarOrdenDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDetalleOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetalleOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_EliminarOrdenDetalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_EliminarUsuario")]
		public ISingleResult<PA_EliminarUsuarioResult> PA_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_EliminarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_ListarUsuario")]
		public ISingleResult<PA_ListarUsuarioResult> PA_ListarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<PA_ListarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_ListaUsuarios")]
		public ISingleResult<PA_ListaUsuariosResult> PA_ListaUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PA_ListaUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_RegistrarUsuario")]
		public ISingleResult<PA_RegistrarUsuarioResult> PA_RegistrarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string nombrePersona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(80)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrePersona, apellido, telefono, cedula, contrasena, correo, idTipoUsuario, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((ISingleResult<PA_RegistrarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarCategoria")]
		public ISingleResult<SP_ActualizarCategoriaResult> SP_ActualizarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria, descripcion, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ActualizarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarProductos")]
		public ISingleResult<SP_ActualizarProductosResult> SP_ActualizarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidadProductos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, precio, idCategoria, cantidadProductos, nombre, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((ISingleResult<SP_ActualizarProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarCategoria")]
		public ISingleResult<SP_AgregarCategoriaResult> SP_AgregarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_AgregarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarProductos")]
		public ISingleResult<SP_AgregarProductosResult> SP_AgregarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), precio, idCategoria, cantidad, nombre, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_AgregarProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CrearOrdenDetalle")]
		public ISingleResult<SP_CrearOrdenDetalleResult> SP_CrearOrdenDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantidad, idOrden, idProducto, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_CrearOrdenDetalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCategoria")]
		public ISingleResult<SP_EliminarCategoriaResult> SP_EliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCateg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCateg, descripcion, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_EliminarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarProductos")]
		public ISingleResult<SP_EliminarProductosResult> SP_EliminarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_EliminarProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GenerarFacturaEfectivo")]
		public ISingleResult<SP_GenerarFacturaEfectivoResult> SP_GenerarFacturaEfectivo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numTelef, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> montoPago, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, nombreCliente, numTelef, montoPago, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_GenerarFacturaEfectivoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GenerarFacturaSinpe")]
		public ISingleResult<SP_GenerarFacturaSinpeResult> SP_GenerarFacturaSinpe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numTelef, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, nombreCliente, numTelef, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_GenerarFacturaSinpeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GenerarFacturaTarjeta")]
		public ISingleResult<SP_GenerarFacturaTarjetaResult> SP_GenerarFacturaTarjeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numTelef, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numTarjeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, nombreCliente, numTelef, numTarjeta, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_GenerarFacturaTarjetaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListaProducto")]
		public ISingleResult<SP_ListaProductoResult> SP_ListaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_ListaProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListaProductos")]
		public ISingleResult<SP_ListaProductosResult> SP_ListaProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListaProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListaProductosOrden")]
		public ISingleResult<SP_ListaProductosOrdenResult> SP_ListaProductosOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_ListaProductosOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCategorias")]
		public ISingleResult<SP_ListarCategoriasResult> SP_ListarCategorias()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarCategoriasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarFacturas")]
		public ISingleResult<SP_ListarFacturasResult> SP_ListarFacturas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarFacturasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarMesas")]
		public ISingleResult<SP_ListarMesasResult> SP_ListarMesas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarMesasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarOrden")]
		public ISingleResult<SP_ListarOrdenResult> SP_ListarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<SP_ListarOrdenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarOrdenes")]
		public ISingleResult<SP_ListarOrdenesResult> SP_ListarOrdenes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarOrdenesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ValidarLogin")]
		public ISingleResult<SP_ValidarLoginResult> SP_ValidarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasena, errorId);
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ValidarLoginResult>)(result.ReturnValue));
		}
	}
	
	public partial class PA_ActualizarOrdenResult
	{
		
		private string _Advertencia;
		
		public PA_ActualizarOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_ActualizarOrdenDetalleResult
	{
		
		private string _Advertencia;
		
		public PA_ActualizarOrdenDetalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_ActualizarUsuarioResult
	{
		
		private string _Advertencia;
		
		public PA_ActualizarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_CancelarOrdenResult
	{
		
		private string _Advertencia;
		
		public PA_CancelarOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_CobrarOrdenResult
	{
		
		private string _Advertencia;
		
		public PA_CobrarOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_CrearOrdenResult
	{
		
		private System.Nullable<decimal> _OrderID;
		
		public PA_CrearOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
	}
	
	public partial class PA_EliminarOrdenResult
	{
		
		private string _Advertencia;
		
		public PA_EliminarOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_EliminarOrdenDetalleResult
	{
		
		private string _Advertencia;
		
		public PA_EliminarOrdenDetalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_EliminarUsuarioResult
	{
		
		private string _Advertencia;
		
		public PA_EliminarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class PA_ListarUsuarioResult
	{
		
		private int _idUsuario;
		
		private int _Persona_ID;
		
		private string _NombrePersona;
		
		private string _Apellido;
		
		private string _correo;
		
		private int _Telefono;
		
		private int _Cedula;
		
		private string _contrasena;
		
		private System.Nullable<int> _idTipoUsuario;
		
		public PA_ListarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_ID", DbType="Int NOT NULL")]
		public int Persona_ID
		{
			get
			{
				return this._Persona_ID;
			}
			set
			{
				if ((this._Persona_ID != value))
				{
					this._Persona_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePersona", DbType="VarChar(80)")]
		public string NombrePersona
		{
			get
			{
				return this._NombrePersona;
			}
			set
			{
				if ((this._NombrePersona != value))
				{
					this._NombrePersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(80)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="Int NOT NULL")]
		public int Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(15)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", DbType="Int")]
		public System.Nullable<int> idTipoUsuario
		{
			get
			{
				return this._idTipoUsuario;
			}
			set
			{
				if ((this._idTipoUsuario != value))
				{
					this._idTipoUsuario = value;
				}
			}
		}
	}
	
	public partial class PA_ListaUsuariosResult
	{
		
		private int _idUsuario;
		
		private string _correo;
		
		private int _Persona_ID;
		
		private string _NombrePersona;
		
		private string _Apellido;
		
		private int _idTipoUsuario;
		
		private string _TipoUsuario;
		
		public PA_ListaUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_ID", DbType="Int NOT NULL")]
		public int Persona_ID
		{
			get
			{
				return this._Persona_ID;
			}
			set
			{
				if ((this._Persona_ID != value))
				{
					this._Persona_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePersona", DbType="VarChar(80)")]
		public string NombrePersona
		{
			get
			{
				return this._NombrePersona;
			}
			set
			{
				if ((this._NombrePersona != value))
				{
					this._NombrePersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(80)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", DbType="Int NOT NULL")]
		public int idTipoUsuario
		{
			get
			{
				return this._idTipoUsuario;
			}
			set
			{
				if ((this._idTipoUsuario != value))
				{
					this._idTipoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="VarChar(15)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
	}
	
	public partial class PA_RegistrarUsuarioResult
	{
		
		private string _Advertencia;
		
		public PA_RegistrarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_ActualizarCategoriaResult
	{
		
		private string _Advertencia;
		
		public SP_ActualizarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_ActualizarProductosResult
	{
		
		private string _Advertencia;
		
		public SP_ActualizarProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_AgregarCategoriaResult
	{
		
		private string _Advertencia;
		
		public SP_AgregarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_AgregarProductosResult
	{
		
		private string _Advertencia;
		
		public SP_AgregarProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_CrearOrdenDetalleResult
	{
		
		private string _Advertencia;
		
		public SP_CrearOrdenDetalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarCategoriaResult
	{
		
		private string _Advertencia;
		
		public SP_EliminarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarProductosResult
	{
		
		private string _Advertencia;
		
		public SP_EliminarProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_GenerarFacturaEfectivoResult
	{
		
		private int _idFactura;
		
		private string _nombreCliente;
		
		private System.Nullable<int> _telefonoCliente;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _montoFactura;
		
		private System.Nullable<decimal> _montoPago;
		
		private System.Nullable<decimal> _vueltoPago;
		
		private System.Nullable<int> _numTarjeta;
		
		private System.Nullable<int> _comprobSinpe;
		
		private System.Nullable<int> _idMesa;
		
		private System.Nullable<int> _idOrden;
		
		private System.Nullable<int> _idUsuario;
		
		private System.Nullable<int> _idTipoPago;
		
		public SP_GenerarFacturaEfectivoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFactura", DbType="Int NOT NULL")]
		public int idFactura
		{
			get
			{
				return this._idFactura;
			}
			set
			{
				if ((this._idFactura != value))
				{
					this._idFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCliente", DbType="VarChar(50)")]
		public string nombreCliente
		{
			get
			{
				return this._nombreCliente;
			}
			set
			{
				if ((this._nombreCliente != value))
				{
					this._nombreCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoCliente", DbType="Int")]
		public System.Nullable<int> telefonoCliente
		{
			get
			{
				return this._telefonoCliente;
			}
			set
			{
				if ((this._telefonoCliente != value))
				{
					this._telefonoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoFactura", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoFactura
		{
			get
			{
				return this._montoFactura;
			}
			set
			{
				if ((this._montoFactura != value))
				{
					this._montoFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoPago
		{
			get
			{
				return this._montoPago;
			}
			set
			{
				if ((this._montoPago != value))
				{
					this._montoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vueltoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> vueltoPago
		{
			get
			{
				return this._vueltoPago;
			}
			set
			{
				if ((this._vueltoPago != value))
				{
					this._vueltoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTarjeta", DbType="Int")]
		public System.Nullable<int> numTarjeta
		{
			get
			{
				return this._numTarjeta;
			}
			set
			{
				if ((this._numTarjeta != value))
				{
					this._numTarjeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comprobSinpe", DbType="Int")]
		public System.Nullable<int> comprobSinpe
		{
			get
			{
				return this._comprobSinpe;
			}
			set
			{
				if ((this._comprobSinpe != value))
				{
					this._comprobSinpe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMesa", DbType="Int")]
		public System.Nullable<int> idMesa
		{
			get
			{
				return this._idMesa;
			}
			set
			{
				if ((this._idMesa != value))
				{
					this._idMesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int")]
		public System.Nullable<int> idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPago", DbType="Int")]
		public System.Nullable<int> idTipoPago
		{
			get
			{
				return this._idTipoPago;
			}
			set
			{
				if ((this._idTipoPago != value))
				{
					this._idTipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_GenerarFacturaSinpeResult
	{
		
		private string _Advertencia;
		
		public SP_GenerarFacturaSinpeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertencia", DbType="NVarChar(4000)")]
		public string Advertencia
		{
			get
			{
				return this._Advertencia;
			}
			set
			{
				if ((this._Advertencia != value))
				{
					this._Advertencia = value;
				}
			}
		}
	}
	
	public partial class SP_GenerarFacturaTarjetaResult
	{
		
		private int _idFactura;
		
		private string _nombreCliente;
		
		private System.Nullable<int> _telefonoCliente;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _montoFactura;
		
		private System.Nullable<decimal> _montoPago;
		
		private System.Nullable<decimal> _vueltoPago;
		
		private System.Nullable<int> _numTarjeta;
		
		private System.Nullable<int> _comprobSinpe;
		
		private System.Nullable<int> _idMesa;
		
		private System.Nullable<int> _idOrden;
		
		private System.Nullable<int> _idUsuario;
		
		private System.Nullable<int> _idTipoPago;
		
		public SP_GenerarFacturaTarjetaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFactura", DbType="Int NOT NULL")]
		public int idFactura
		{
			get
			{
				return this._idFactura;
			}
			set
			{
				if ((this._idFactura != value))
				{
					this._idFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCliente", DbType="VarChar(50)")]
		public string nombreCliente
		{
			get
			{
				return this._nombreCliente;
			}
			set
			{
				if ((this._nombreCliente != value))
				{
					this._nombreCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoCliente", DbType="Int")]
		public System.Nullable<int> telefonoCliente
		{
			get
			{
				return this._telefonoCliente;
			}
			set
			{
				if ((this._telefonoCliente != value))
				{
					this._telefonoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoFactura", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoFactura
		{
			get
			{
				return this._montoFactura;
			}
			set
			{
				if ((this._montoFactura != value))
				{
					this._montoFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoPago
		{
			get
			{
				return this._montoPago;
			}
			set
			{
				if ((this._montoPago != value))
				{
					this._montoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vueltoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> vueltoPago
		{
			get
			{
				return this._vueltoPago;
			}
			set
			{
				if ((this._vueltoPago != value))
				{
					this._vueltoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTarjeta", DbType="Int")]
		public System.Nullable<int> numTarjeta
		{
			get
			{
				return this._numTarjeta;
			}
			set
			{
				if ((this._numTarjeta != value))
				{
					this._numTarjeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comprobSinpe", DbType="Int")]
		public System.Nullable<int> comprobSinpe
		{
			get
			{
				return this._comprobSinpe;
			}
			set
			{
				if ((this._comprobSinpe != value))
				{
					this._comprobSinpe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMesa", DbType="Int")]
		public System.Nullable<int> idMesa
		{
			get
			{
				return this._idMesa;
			}
			set
			{
				if ((this._idMesa != value))
				{
					this._idMesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int")]
		public System.Nullable<int> idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPago", DbType="Int")]
		public System.Nullable<int> idTipoPago
		{
			get
			{
				return this._idTipoPago;
			}
			set
			{
				if ((this._idTipoPago != value))
				{
					this._idTipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_ListaProductoResult
	{
		
		private int _idProducto;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private int _idCategoria;
		
		private string _descripcion;
		
		public SP_ListaProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListaProductosResult
	{
		
		private int _idProducto;
		
		private System.Nullable<decimal> _precio;
		
		private int _idCategoria;
		
		private System.Nullable<int> _cantidadProductos;
		
		private string _nombre;
		
		public SP_ListaProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadProductos", DbType="Int")]
		public System.Nullable<int> cantidadProductos
		{
			get
			{
				return this._cantidadProductos;
			}
			set
			{
				if ((this._cantidadProductos != value))
				{
					this._cantidadProductos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
	
	public partial class SP_ListaProductosOrdenResult
	{
		
		private int _idOrden;
		
		private int _idProducto;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private int _idCategoria;
		
		private string _cantidad;
		
		public SP_ListaProductosOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int NOT NULL")]
		public int idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProducto", DbType="Int NOT NULL")]
		public int idProducto
		{
			get
			{
				return this._idProducto;
			}
			set
			{
				if ((this._idProducto != value))
				{
					this._idProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
	}
	
	public partial class SP_ListarCategoriasResult
	{
		
		private int _idCategoria;
		
		private string _descripcion;
		
		public SP_ListarCategoriasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this._idCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarFacturasResult
	{
		
		private int _idFactura;
		
		private string _nombreCliente;
		
		private System.Nullable<int> _telefonoCliente;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _montoFactura;
		
		private System.Nullable<decimal> _montoPago;
		
		private System.Nullable<decimal> _vueltoPago;
		
		private System.Nullable<int> _numTarjeta;
		
		private System.Nullable<int> _comprobSinpe;
		
		private System.Nullable<int> _idMesa;
		
		private System.Nullable<int> _idOrden;
		
		private System.Nullable<int> _idUsuario;
		
		private System.Nullable<int> _idTipoPago;
		
		public SP_ListarFacturasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFactura", DbType="Int NOT NULL")]
		public int idFactura
		{
			get
			{
				return this._idFactura;
			}
			set
			{
				if ((this._idFactura != value))
				{
					this._idFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCliente", DbType="VarChar(50)")]
		public string nombreCliente
		{
			get
			{
				return this._nombreCliente;
			}
			set
			{
				if ((this._nombreCliente != value))
				{
					this._nombreCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoCliente", DbType="Int")]
		public System.Nullable<int> telefonoCliente
		{
			get
			{
				return this._telefonoCliente;
			}
			set
			{
				if ((this._telefonoCliente != value))
				{
					this._telefonoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoFactura", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoFactura
		{
			get
			{
				return this._montoFactura;
			}
			set
			{
				if ((this._montoFactura != value))
				{
					this._montoFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoPago
		{
			get
			{
				return this._montoPago;
			}
			set
			{
				if ((this._montoPago != value))
				{
					this._montoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vueltoPago", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> vueltoPago
		{
			get
			{
				return this._vueltoPago;
			}
			set
			{
				if ((this._vueltoPago != value))
				{
					this._vueltoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTarjeta", DbType="Int")]
		public System.Nullable<int> numTarjeta
		{
			get
			{
				return this._numTarjeta;
			}
			set
			{
				if ((this._numTarjeta != value))
				{
					this._numTarjeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comprobSinpe", DbType="Int")]
		public System.Nullable<int> comprobSinpe
		{
			get
			{
				return this._comprobSinpe;
			}
			set
			{
				if ((this._comprobSinpe != value))
				{
					this._comprobSinpe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMesa", DbType="Int")]
		public System.Nullable<int> idMesa
		{
			get
			{
				return this._idMesa;
			}
			set
			{
				if ((this._idMesa != value))
				{
					this._idMesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int")]
		public System.Nullable<int> idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPago", DbType="Int")]
		public System.Nullable<int> idTipoPago
		{
			get
			{
				return this._idTipoPago;
			}
			set
			{
				if ((this._idTipoPago != value))
				{
					this._idTipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_ListarMesasResult
	{
		
		private int _idMesa;
		
		private string _nombreMesa;
		
		public SP_ListarMesasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMesa", DbType="Int NOT NULL")]
		public int idMesa
		{
			get
			{
				return this._idMesa;
			}
			set
			{
				if ((this._idMesa != value))
				{
					this._idMesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMesa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombreMesa
		{
			get
			{
				return this._nombreMesa;
			}
			set
			{
				if ((this._nombreMesa != value))
				{
					this._nombreMesa = value;
				}
			}
		}
	}
	
	public partial class SP_ListarOrdenResult
	{
		
		private int _idOrden;
		
		private System.Nullable<decimal> _montoOrden;
		
		public SP_ListarOrdenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int NOT NULL")]
		public int idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoOrden", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> montoOrden
		{
			get
			{
				return this._montoOrden;
			}
			set
			{
				if ((this._montoOrden != value))
				{
					this._montoOrden = value;
				}
			}
		}
	}
	
	public partial class SP_ListarOrdenesResult
	{
		
		private int _idOrden;
		
		private string _nombreMesa;
		
		public SP_ListarOrdenesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrden", DbType="Int NOT NULL")]
		public int idOrden
		{
			get
			{
				return this._idOrden;
			}
			set
			{
				if ((this._idOrden != value))
				{
					this._idOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMesa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombreMesa
		{
			get
			{
				return this._nombreMesa;
			}
			set
			{
				if ((this._nombreMesa != value))
				{
					this._nombreMesa = value;
				}
			}
		}
	}
	
	public partial class SP_ValidarLoginResult
	{
		
		private int _idUsuario;
		
		private System.Nullable<int> _idTipoUsuario;
		
		private string _NombrePersona;
		
		private string _Apellido;
		
		public SP_ValidarLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", DbType="Int")]
		public System.Nullable<int> idTipoUsuario
		{
			get
			{
				return this._idTipoUsuario;
			}
			set
			{
				if ((this._idTipoUsuario != value))
				{
					this._idTipoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePersona", DbType="VarChar(80)")]
		public string NombrePersona
		{
			get
			{
				return this._NombrePersona;
			}
			set
			{
				if ((this._NombrePersona != value))
				{
					this._NombrePersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(80)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
